GET http://localhost:3000/messages

### Post Message
POST http://localhost:3000/messages
content-type : application/json

{
    "content": "Test"
}

### Get Message by ID
GET http://localhost:3000/messages/170